import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const resume = '/Guddu-Kumar-Resume.pdf';
const links = { github:'https://github.com/Guddu-Kumar123', linkedin:'https://linkedin.com/in/guddu180499', email:'mailto:guddu931811@gmail.com', phone:'tel:+916200931811' };
const skillGroups = [
 ['Programming', ['Java (8/11/17)','SQL','JavaScript (ES6)','HTML5','CSS3']],
 ['Backend', ['Spring Boot','Spring Framework','Spring Security','RESTful APIs','Hibernate','JPA','Microservices']],
 ['Frontend', ['React.js','Redux','JavaScript','HTML5','CSS3']],
 ['Data', ['MySQL','PostgreSQL','Redis']],
 ['Tools', ['Git','GitHub','Docker','Maven','Gradle','Postman','CI/CD','AWS']],
 ['Foundations', ['DSA','OOP','DBMS','Operating Systems','Networking','Software Engineering']]
];
const projects = [
 {name:'SmartBank', type:['Java','Spring Boot','React','Full Stack'], date:'Feb 2025', tagline:'Secure modern digital banking system', description:'A secure full-stack Internet Banking System using Spring Boot, React.js, and MySQL, featuring JWT-based authentication, a role-based admin panel, and real-time transaction management.', tech:['Spring Boot','React.js','MySQL','Spring Security','JWT','GitHub Actions','Docker'], features:['Account creation','Money transfers','Loan management','JWT authentication','Role-based admin panel','Transaction management'], architecture:['React.js','REST API','Spring Boot','Spring Security / JWT','MySQL'], github:'', live:'', notes:'Add project repository and deployment links in src/main.jsx.'},
 {name:'E-Commerce Website', type:['Java','Spring Boot','React','Full Stack'], date:'Aug 2024', tagline:'Java full-stack e-commerce platform', description:'A full-stack e-commerce platform with a product catalog, cart, secure checkout, Spring Boot REST APIs, and a React.js frontend connected via Axios.', tech:['Spring Boot','React.js','MySQL','REST APIs','Axios','GitHub Actions','Docker'], features:['Product catalog','Product management','Shopping cart','Secure checkout','REST APIs','React frontend'], architecture:['React.js','Axios','Spring Boot REST API','MySQL'], github:'', live:'', notes:'Add project repository and deployment links in src/main.jsx.'}
];
const sections=['Home','About','Skills','Projects','Experience','Education','Certifications','Contact'];
function Icon({children}){return <span className="icon" aria-hidden="true">{children}</span>}
function Nav(){const [open,setOpen]=useState(false);const [active,setActive]=useState('Home'); useEffect(()=>{const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&setActive(e.target.dataset.name)),{rootMargin:'-35% 0px -55%'}); document.querySelectorAll('section[data-name]').forEach(x=>obs.observe(x));return()=>obs.disconnect()},[]); return <header><a className="brand" href="#home" aria-label="Guddu Kumar home">GK<span>.</span></a><button className="menu" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Toggle navigation">{open?'×':'☰'}</button><nav className={open?'open':''}>{sections.map(s=><a className={active===s?'active':''} onClick={()=>setOpen(false)} href={'#'+s.toLowerCase()} key={s}>{s}</a>)}<a className="social" href={links.github} aria-label="GitHub">◖</a><a className="social" href={links.linkedin} aria-label="LinkedIn">in</a><a className="resume-nav" href={resume} download>Résumé ↗</a></nav></header>}
function Hero(){const roles=['Java Full Stack Developer','Java Developer','Spring Boot Developer','Backend Developer','React.js Developer'];const [r,setR]=useState(0);useEffect(()=>{const id=setInterval(()=>setR(x=>(x+1)%roles.length),2400);return()=>clearInterval(id)},[]);return <section id="home" data-name="Home" className="hero"><div className="hero-copy"><p className="eyebrow"><span/> Available for software engineering opportunities</p><h1>Hi, I’m <em>Guddu Kumar</em></h1><div className="role">{roles[r]}</div><p className="lead">Java Full Stack Developer with hands-on experience in Spring Boot, Hibernate, React.js, RESTful APIs, MySQL, and modern software development practices.</p><div className="actions"><a className="button primary" href="#projects">View my projects <b>→</b></a><a className="button" href={resume} download>Download résumé ↓</a><a className="text-link" href="#contact">Contact me</a></div><div className="socials"><a href={links.github}>GitHub ↗</a><a href={links.linkedin}>LinkedIn ↗</a><a href={links.email}>Email ↗</a></div></div><div className="code-orbit" aria-hidden="true"><div className="orb glow"/><div className="terminal"><div className="terminal-bar"><i/><i/><i/><span>guddu.dev</span></div><code><small>01</small> <b>public class</b> Developer {'{'}<br/><small>02</small> &nbsp; <b>String</b> focus =<br/><small>03</small> &nbsp; <span>"clean software"</span>;<br/><small>04</small> {'}'}</code></div>{['Java','Spring Boot','React','MySQL','Docker'].map((x,i)=><span className={'tech t'+i} key={x}>{x}</span>)}</div></section>}
function About(){return <section id="about" data-name="About" className="section"><Tag>01 / About</Tag><h2>Building reliable software with <em>Java</em> and modern web technologies.</h2><div className="about"><p>I’m a Java Full Stack Developer focused on thoughtful backend architecture and complete web experiences. My practical toolkit spans Spring Boot, Hibernate, JPA, React.js, REST APIs, relational databases, Docker, Git/GitHub, and CI/CD.</p><div className="highlights">{[['⌘','Java & backend','Building with Spring Boot, Hibernate, JPA and REST APIs.'],['◫','Full stack','Connecting React.js interfaces to reliable services.'],['↗','Problem solving','Grounded in DSA, OOP and software engineering.'],['⊞','Data & APIs','Working with MySQL, PostgreSQL and API design.']].map(x=><article key={x[1]}><Icon>{x[0]}</Icon><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>}
function Tag({children}){return <p className="tag">{children}</p>}
function Skills(){return <section id="skills" data-name="Skills" className="section tint"><Tag>02 / Technical toolkit</Tag><h2>Tools I use to turn ideas into <em>working products.</em></h2><div className="skills">{skillGroups.map(([name,skills])=><article className="skill-group" key={name}><h3>{name}</h3><div>{skills.map(s=><span key={s}>{s}</span>)}</div></article>)}</div></section>}
function Projects(){const [filter,setFilter]=useState('All');const [chosen,setChosen]=useState(null);const shown=projects.filter(p=>filter==='All'||p.type.includes(filter));return <section id="projects" data-name="Projects" className="section"><Tag>03 / Selected work</Tag><h2>Projects with an emphasis on <em>useful systems.</em></h2><div className="filters">{['All','Java','Spring Boot','React','Full Stack'].map(x=><button onClick={()=>setFilter(x)} className={filter===x?'selected':''} key={x}>{x}</button>)}</div><div className="projects">{shown.map((p,i)=><article className="project" key={p.name}><div className={'project-art art'+i}><span>{i?'commerce':'banking'}</span><div className="mini-ui"><b>{i?'Storefront':'SmartBank'}</b><i/><i/><i/></div></div><div className="project-copy"><div className="project-top"><p>{p.date}</p><strong>{p.type.slice(0,2).join(' / ')}</strong></div><h3>{p.name}</h3><h4>{p.tagline}</h4><p>{p.description}</p><div className="pills">{p.tech.map(t=><span key={t}>{t}</span>)}</div><div className="project-actions"><button className="plain-button" onClick={()=>setChosen(p)}>View case study →</button>{p.github?<a href={p.github}>GitHub ↗</a>:<span title={p.notes}>GitHub (add link)</span>}{p.live?<a href={p.live}>Live demo ↗</a>:<span title={p.notes}>Demo (add link)</span>}</div></div></article>)}</div>{chosen&&<Modal p={chosen} close={()=>setChosen(null)}/>}</section>}
function Modal({p,close}){return <div className="modal-back" role="presentation" onMouseDown={close}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close} aria-label="Close case study">×</button><Tag>Case study / {p.date}</Tag><h2 id="modal-title">{p.name}</h2><p>{p.description}</p><div className="case-grid"><div><h3>Key features</h3><ul>{p.features.map(x=><li key={x}>{x}</li>)}</ul></div><div><h3>Architecture</h3><ol>{p.architecture.map(x=><li key={x}>{x}</li>)}</ol></div></div><p className="note">{p.notes}</p></section></div>}
function Experience(){return <section id="experience" data-name="Experience" className="section tint"><Tag>04 / Experience</Tag><h2>Learning by <em>building.</em></h2><div className="timeline"><article><p>Jun 2023</p><div><h3>Web Developer Intern</h3><h4>In-House Summer Internship</h4><ul><li>Developed a mini full-stack web project using HTML, CSS, JavaScript, and MySQL.</li><li>Implemented REST APIs and frontend-backend integration.</li><li>Improved understanding of deployment and version control using Git.</li></ul></div></article></div></section>}
function Education(){const items=[['2022 – 2025','B.E. Computer Science and Engineering','Chandigarh University, Mohali, Punjab','CGPA: 7.3','Data Structures · DBMS · Operating Systems · Software Engineering'],['2017','Intermediate','RNTS College Morsand, Sitamarhi, Bihar','Percentage: 62%',''],['2014','Matriculation','MVG High School, Manik Chauk, Sitamarhi, Bihar','Percentage: 72%','']];return <section id="education" data-name="Education" className="section"><Tag>05 / Education</Tag><h2>Strong fundamentals, built for <em>continuous learning.</em></h2><div className="education">{items.map(x=><article key={x[0]+x[1]}><p>{x[0]}</p><div><h3>{x[1]}</h3><h4>{x[2]}</h4><strong>{x[3]}</strong>{x[4]&&<small>{x[4]}</small>}</div></article>)}</div></section>}
function Certifications(){const certs=[['Developing AI Applications with Python and Flask','IBM'],['The Complete React JS and Redux Course - Build Modern Web Apps','Infosys'],['HTML, CSS, JavaScript Certification','Infosys']];return <section id="certifications" data-name="Certifications" className="section tint"><Tag>06 / Certifications</Tag><h2>Continuing to <em>sharpen the craft.</em></h2><div className="certs">{certs.map(([n,o],i)=><article key={n}><span>0{i+1}</span><Icon>✦</Icon><h3>{n}</h3><p>{o}</p></article>)}</div></section>}
function Github(){return <section className="section github"><Tag>07 / GitHub activity</Tag><div className="github-card"><div className="github-mark" aria-hidden="true">◖</div><div><h2>Building in the <em>open.</em></h2><p>Explore Guddu’s repositories and ongoing development work on GitHub.</p><a className="button" href={links.github}>View GitHub profile ↗</a></div><div className="github-handle"><small>github.com</small><strong>Guddu-Kumar123</strong><span>Profile and repositories</span></div></div></section>}
function Contact(){const [copied,setCopied]=useState(false); function submit(e){e.preventDefault(); const f=new FormData(e.currentTarget); window.location.href=`mailto:guddu931811@gmail.com?subject=${encodeURIComponent(f.get('subject'))}&body=${encodeURIComponent(`Name: ${f.get('name')}\nEmail: ${f.get('email')}\n\n${f.get('message')}`)}`};return <><section className="resume-cta"><p>Want to know more about my experience?</p><h2>Explore the details behind my work.</h2><a className="button primary" href={resume} download>Download résumé ↓</a><a className="text-link" href={resume} target="_blank">View résumé ↗</a></section><section id="contact" data-name="Contact" className="section contact"><Tag>07 / Get in touch</Tag><h2>Let’s build something <em>together.</em></h2><div className="contact-grid"><div><p className="lead">I’m open to software engineering opportunities, collaborations, and interesting development projects.</p><a href={links.email}>guddu931811@gmail.com</a><button className="copy" onClick={()=>{navigator.clipboard.writeText('guddu931811@gmail.com');setCopied(true)}}>{copied?'Copied!':'Copy email'}</button><a href={links.phone}>+91 6200931811</a><a href={links.linkedin}>LinkedIn ↗</a><a href={links.github}>GitHub ↗</a></div><form onSubmit={submit}><label>Name<input name="name" required/></label><label>Email<input name="email" type="email" required/></label><label>Subject<input name="subject" required/></label><label>Message<textarea name="message" required rows="4"/></label><button className="button primary">Open email client →</button><small>This form opens your email client; no message is sent by this site.</small></form></div></section></>}
function Footer(){const [top,setTop]=useState(false);useEffect(()=>{const x=()=>setTop(scrollY>600);addEventListener('scroll',x);return()=>removeEventListener('scroll',x)},[]);return <footer><div><a className="brand" href="#home">GK<span>.</span></a><p>Java Full Stack Developer</p></div><p>© 2026 Guddu Kumar. All rights reserved. <span>Built with React.js</span></p>{top&&<button className="to-top" onClick={()=>scrollTo({top:0,behavior:'smooth'})} aria-label="Back to top">↑</button>}</footer>}
function App(){const [light,setLight]=useState(false);return <div className={light?'light':''}><button className="theme" onClick={()=>setLight(!light)} aria-label="Toggle color theme">{light?'☾':'☀'}</button><Nav/><main><Hero/><About/><Skills/><Projects/><Experience/><Education/><Certifications/><Github/><Contact/></main><Footer/></div>}; createRoot(document.getElementById('root')).render(<App/>);
